// ============================================================
// AskElira CLI — completion command
// ============================================================
// `askelira completion bash` — output bash completion script
// `askelira completion zsh` — output zsh completion script
// `askelira completion install` — auto-install to rc file

import chalk from 'chalk';
import fs from 'fs';
import os from 'os';
import path from 'path';

const COMMANDS = [
  'login', 'logout', 'whoami',
  'build', 'status', 'floors', 'logs', 'watch',
  'run', 'rollback', 'workspace',
  'start', 'stop', 'heartbeat',
  'init', 'completion',
];

const BASH_COMPLETION = `# AskElira CLI bash completion
# Generated by: askelira completion bash
_askelira_completions()
{
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local commands="${COMMANDS.join(' ')}"

  if [ "\${COMP_CWORD}" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
    return 0
  fi

  local cmd="\${COMP_WORDS[1]}"
  case "\${cmd}" in
    logs)
      local opts="--tail --agent --floor"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
    run)
      local opts="--floor --dry-run"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
    heartbeat)
      local opts="--trigger"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
    status|floors)
      local opts="--json"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
    completion)
      local opts="bash zsh install"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
    workspace)
      local opts="ls cat open"
      COMPREPLY=( $(compgen -W "\${opts}" -- "\${cur}") )
      ;;
  esac
  return 0
}
complete -F _askelira_completions askelira
`;

const ZSH_COMPLETION = `# AskElira CLI zsh completion
# Generated by: askelira completion zsh
_askelira() {
  local -a commands
  commands=(
    'login:Authenticate with your AskElira account'
    'logout:Clear stored credentials'
    'whoami:Show current logged-in user'
    'build:Create a new goal and start building'
    'status:Show status of a goal or all goals'
    'floors:List floors for a goal'
    'logs:View agent logs for a goal'
    'watch:Live dashboard'
    'run:Trigger a heartbeat check manually'
    'rollback:Rollback a floor to a previous snapshot'
    'workspace:View workspace files'
    'start:Start the heartbeat monitor'
    'stop:Stop the heartbeat monitor'
    'heartbeat:View heartbeat status'
    'init:Setup wizard'
    'completion:Shell completion scripts'
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case "\$state" in
    command)
      _describe -t commands 'askelira command' commands
      ;;
    args)
      case "\$words[1]" in
        logs)
          _arguments \\
            '--tail[Poll for new logs]' \\
            '--agent[Filter by agent name]:agent:(Alba Vex David Elira Steven)' \\
            '--floor[Filter by floor ID]:floor:'
          ;;
        run)
          _arguments \\
            '--floor[Check specific floor]:floor:' \\
            '--dry-run[Show what would run]'
          ;;
        heartbeat)
          _arguments \\
            '--trigger[Run one heartbeat cycle]'
          ;;
        status|floors)
          _arguments \\
            '--json[Output as JSON]'
          ;;
        completion)
          _arguments '1:shell:(bash zsh install)'
          ;;
        workspace)
          _arguments '1:subcommand:(ls cat open)'
          ;;
      esac
      ;;
  esac
}
compdef _askelira askelira
`;

/**
 * Main completion command handler.
 */
export function completionCommand(shell?: string): void {
  if (!shell) {
    console.log('');
    console.log(chalk.bold('  Shell Completion'));
    console.log('');
    console.log('  Usage:');
    console.log(`    ${chalk.cyan('askelira completion bash')}    ${chalk.gray('Output bash completion script')}`);
    console.log(`    ${chalk.cyan('askelira completion zsh')}     ${chalk.gray('Output zsh completion script')}`);
    console.log(`    ${chalk.cyan('askelira completion install')} ${chalk.gray('Auto-install to your shell config')}`);
    console.log('');
    console.log('  Manual install:');
    console.log(chalk.gray('    askelira completion bash >> ~/.bashrc'));
    console.log(chalk.gray('    askelira completion zsh >> ~/.zshrc'));
    console.log('');
    return;
  }

  if (shell === 'bash') {
    process.stdout.write(BASH_COMPLETION);
    return;
  }

  if (shell === 'zsh') {
    process.stdout.write(ZSH_COMPLETION);
    return;
  }

  if (shell === 'install') {
    installCompletion();
    return;
  }

  console.log(chalk.red(`  Unknown shell: ${shell}`));
  console.log(chalk.gray('  Supported: bash, zsh, install'));
  process.exitCode = 1;
}

/**
 * Auto-install completion to the appropriate rc file.
 */
function installCompletion(): void {
  const shellEnv = process.env.SHELL || '';
  const isZsh = shellEnv.includes('zsh');
  const isBash = shellEnv.includes('bash');

  if (!isZsh && !isBash) {
    console.log(chalk.yellow('  Could not detect shell type from $SHELL.'));
    console.log(chalk.gray('  Manually pipe output to your rc file:'));
    console.log(chalk.gray('    askelira completion bash >> ~/.bashrc'));
    console.log(chalk.gray('    askelira completion zsh >> ~/.zshrc'));
    process.exitCode = 1;
    return;
  }

  const rcFile = isZsh
    ? path.join(os.homedir(), '.zshrc')
    : path.join(os.homedir(), '.bashrc');

  const completionScript = isZsh ? ZSH_COMPLETION : BASH_COMPLETION;
  const marker = '# AskElira CLI';

  // Check if already installed
  try {
    const existing = fs.readFileSync(rcFile, 'utf-8');
    if (existing.includes(marker)) {
      console.log(chalk.yellow(`  Completion already installed in ${rcFile}`));
      console.log(chalk.gray('  Remove the existing block and re-run to update.'));
      return;
    }
  } catch {
    // File doesn't exist yet, we'll create it
  }

  try {
    fs.appendFileSync(rcFile, '\n' + completionScript + '\n');
    console.log(chalk.green(`  Completion installed to ${rcFile}`));
    console.log(chalk.gray(`  Restart your shell or run: source ${rcFile}`));
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    console.log(chalk.red(`  Failed to write to ${rcFile}: ${message}`));
    process.exitCode = 1;
  }
}
